# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_color_display_hd_memory_os_processor_productpage_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='conv',
            field=models.BooleanField(default=False),
        ),
    ]
