# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productpage_conv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='brandtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand'),
        ),
    ]
