# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170815_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
