# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170815_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='articleid',
        ),
        migrations.AlterField(
            model_name='productpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
    ]
