# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20170815_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('friendly_name', models.CharField(max_length=200)),
                ('country_choice', models.CharField(choices=[('United States', 'US'), ('Canada', 'CA')], default='United States', max_length=15)),
                ('status_choices', models.CharField(choices=[('Live', 'Live'), ('Not Live', 'Not Live/Removed From Site'), ('Blocked', 'Blocked'), ('Temporarily Unavailable', 'Temporarily Unavailable')], default='Live', max_length=200)),
                ('type_choices', models.CharField(choices=[('Made to Manufacture', 'Made to Manufacture'), ('Configurable to Order', 'Configurable to Order')], default='Made to Manufacture', max_length=200)),
                ('sku_link', models.TextField(default='NULL')),
                ('price_choice', models.CharField(choices=[('1', 'Above $3,000'), ('2', 'Between $1,000 - $2999.99'), ('3', 'Between $500 - $999.99'), ('4', 'Between $100 - $499.99')], default='3', max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_date', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ProductPage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('color_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color')),
                ('display_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Display')),
                ('hd_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Hd')),
                ('memory_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Memory')),
                ('os_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Os')),
                ('processor_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Processor')),
                ('ss_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Ss')),
            ],
        ),
    ]
