# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('product', '0009_auto_20171126_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Pretty Banner Image :)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='productindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text to descript the index of the products'),
        ),
    ]
