# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 02:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20171127_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text to describe the index of the products'),
        ),
    ]
