# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:03
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20171127_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='product.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
