# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:06
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20171231_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='product.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
