# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20171231_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='product.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='product.ProductPage'),
        ),
    ]
