# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 00:35
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20171231_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
