# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 00:47
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('product', '0015_auto_20180116_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='productpage',
            name='producttag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='product.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
