# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 01:46
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20180122_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='producttag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
