# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=b'media')),
                ('desc', models.TextField(help_text=b'Describe Logo')),
            ],
        ),
    ]
