# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171222_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='desc',
            field=models.TextField(help_text='Describe Logo'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='icon',
            field=models.ForeignKey(blank=True, default='https://image.flaticon.com/icons/svg/25/25284.svg', help_text='icon for your link.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='link',
            field=models.URLField(blank=True, help_text='url'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='title',
            field=models.TextField(help_text='Name of Resource', max_length=255),
        ),
    ]
